# See https://help.github.com/en/actions/automating-your-workflow-with-github-actions/workflow-syntax-for-github-actions

name: 'build'

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']
  schedule:
    - cron: '0 0 * * 6'

jobs:
  build:
    runs-on: 'ubuntu-latest'
    steps:
      - name: Checkout
        uses: 'actions/checkout@v4'
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of sonar analysis

      - name: Set up Java
        uses: 'actions/setup-java@v3'
        with:
          distribution: 'temurin'
          java-version: 17
          cache: 'maven'

      - name: Cache SonarQube packages
        uses: 'actions/cache@v3'
        with:
          path: '~/.sonar/cache'
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Cache Maven packages
        uses: 'actions/cache@v3'
        with:
          path: '~/.m2/repository'
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-

      - name: Build
        run: 'mvn --settings .mvn/settings.xml -B verify'

      # See https://docs.sonarqube.org/latest/analysis/github-integration/
      - name: Analyze
        # This workflow is only of value to the marcwrobel/parent repository and would always fail in forks
        if: github.repository == 'marcwrobel/parent'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Needed to get PR information, if any
          SONAR_LOGIN: ${{ secrets.SONAR_LOGIN }} # Needed to connect to sonarcloud
        run: 'mvn --settings .mvn/settings.xml -B sonar:sonar'
